language: python
python:
  - "2.7"

virtualenv:
    system_site_packages: true

addons:
    apt:
        packages:
            - python-numpy 
            - python-scipy 
            - libblas-dev 
            - liblapack-dev
            - gfortran
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
